# @format

version: "3"
services:
  app:
    container_name: app_front_container
    build:
      context: .
      dockerfile: skill-oasis/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./skill-oasis:/app
    stdin_open: true
    tty: true


